### ISSUE TITLE
Pre release version for branch test-electron-app-4964 not available

### ISSUE THREAD

**Issue by clucasalcantara** [cypress-io/cypress-electron-plugin#4]
The last build for `test-electron-app-4964` hasn't an available pre-release bundle for install. Also, previous commits haven't darwin version to mac installs.

How to get the proper pre-release bundle to use the electron-sandbox runner after update the `plugins/index.js` file? 

Adding the snippet below without the right rest runner results into 
```
An invalid configuration value returned from the plugins file: cypress/plugins/index.js

Found an error while validating the browsers list. Expected family to be either chromium or firefox. Instead the value was: {"name":"electron-sandbox","family":"electron-app","displayName":"electron-sandbox","version":"3.0.0","path":"/Users/clucasalcantara/projects/ark/desktop-wallet/node_modules/.bin/electron","majorVersion":"v3.0.0","info":"Ark Ecosystem Desktop Wallet"}
```

Plugins config snippet:
```
const path = require("path");
const pkg = require("../../package");

const pathToElectron = path.join(__dirname, "..", "..", "node_modules", ".bin", "electron");
module.exports = (on, config) => {
	// remove "standard" browsers and use
	// our local Electron as a browser
	config.browsers = [
		{
			name: "electron-sandbox",
			family: "electron-app",
			displayName: "electron-sandbox",
			version: pkg.version,
			path: pathToElectron,
			// show full package version in the browser dropdown
			majorVersion: `v${pkg.version}`,
			info: pkg.description || "Electron.js app that supports the Cypress launcher",
		},
	];

	return config;
};
```

Installed cypress electron plugin version: "@cypress/electron-plugin": "^1.1.0"

Last commit into test-electron-app-4964: https://github.com/cypress-io/cypress/commit/aed924e2ef1047ab9e5b9b7dcab38a7ee5cc2c09

Last commit with the prerelease build (no darwin version): https://github.com/cypress-io/cypress/commit/72c9c7dbe403133b97268532f267be3cfab79737

**Comment by bahmutov** [comment]
Currently, we do not have plans or resources to maintain this branch, we apologize.

**Comment by clucasalcantara** [comment]
Closing the issue then. Thanks @bahmutov!
